---
name: Courier-Filter
version: 0.17
author:
  - Julian Mehnle <julian@mehnle.net>
abstract: A purely Perl-based mail filter framework for the Courier MTA
license: perl
requires:
  Encode: 0
  Error: 0
  IO::File: 0
  IO::Handle: 0
  IO::Select: 0
  IO::Socket::UNIX: 0
  perl: 5.8
recommends:
  Archive::Zip: 0
  ClamAV::Client: 0
  Digest::MD5: 0
  File::Spec: 0
  IO::InnerFile: 2.110
  MIME::Tools: 5.4
  Mail::SPF::Query: 1.991
  Mail::SpamAssassin: 0
  Net::Address::IPv4::Local: 0
  Net::DNS: 0
  Net::RBLClient: 0
build_requires:
  Test::Simple: 0
provides:
  Courier::Config:
    file: lib/Courier/Config.pm
    version: 0.17
  Courier::Error:
    file: lib/Courier/Error.pm
    version: 0.17
  Courier::Filter:
    file: lib/Courier/Filter.pm
    version: 0.17
  Courier::Filter::Logger:
    file: lib/Courier/Filter/Logger.pm
    version: 0.17
  Courier::Filter::Logger::File:
    file: lib/Courier/Filter/Logger/File.pm
    version: 0.17
  Courier::Filter::Logger::IOHandle:
    file: lib/Courier/Filter/Logger/IOHandle.pm
    version: 0.17
  Courier::Filter::Logger::Syslog:
    file: lib/Courier/Filter/Logger/Syslog.pm
    version: 0.17
  Courier::Filter::Module:
    file: lib/Courier/Filter/Module.pm
    version: 0.17
  Courier::Filter::Module::ClamAVd:
    file: lib/Courier/Filter/Module/ClamAVd.pm
    version: 0.17
  Courier::Filter::Module::DNSBL:
    file: lib/Courier/Filter/Module/DNSBL.pm
    version: 0.17
  Courier::Filter::Module::Envelope:
    file: lib/Courier/Filter/Module/Envelope.pm
    version: 0.17
  Courier::Filter::Module::Header:
    file: lib/Courier/Filter/Module/Header.pm
    version: 0.17
  Courier::Filter::Module::MIMEParts:
    file: lib/Courier/Filter/Module/MIMEParts.pm
    version: 0.17
  Courier::Filter::Module::Parts:
    file: lib/Courier/Filter/Module/Parts.pm
    version: 0.17
  Courier::Filter::Module::SPF:
    file: lib/Courier/Filter/Module/SPF.pm
    version: 0.17
  Courier::Filter::Module::SPFout:
    file: lib/Courier/Filter/Module/SPFout.pm
    version: 0.17
  Courier::Filter::Module::SpamAssassin:
    file: lib/Courier/Filter/Module/SpamAssassin.pm
    version: 0.17
  Courier::Message:
    file: lib/Courier/Message.pm
    version: 0.17
  MIME::Words::Better:
    file: lib/Courier/Message.pm
    version: 0.17
generated_by: Module::Build version 0.26
