--- #YAML:1.0
name: Courier-Filter
version: 0.11
license: perl
distribution_type: module
requires:
  Encode: 0
  Error: 0
  IO::File: 0
  IO::Handle: 0
  IO::Select: 0
  IO::Socket::UNIX: 0
  perl: 5.8
recommends:
  Digest::MD5: 0
  MIME::Tools: 5.4
  Mail::SPF::Query: 1.991
  Net::RBLClient: 0
build_requires: {}
conflicts: {}
provides:
  Courier::Config:
    file: lib/Courier/Config.pm
    version: 0.11
  Courier::Error:
    file: lib/Courier/Error.pm
    version: 0.11
  Courier::Filter:
    file: lib/Courier/Filter.pm
    version: 0.11
  Courier::Filter::Logger:
    file: lib/Courier/Filter/Logger.pm
    version: 0.11
  Courier::Filter::Logger::File:
    file: lib/Courier/Filter/Logger/File.pm
    version: 0.11
  Courier::Filter::Logger::IOHandle:
    file: lib/Courier/Filter/Logger/IOHandle.pm
    version: 0.11
  Courier::Filter::Logger::Syslog:
    file: lib/Courier/Filter/Logger/Syslog.pm
    version: 0.11
  Courier::Filter::Module:
    file: lib/Courier/Filter/Module.pm
    version: 0.11
  Courier::Filter::Module::DNSBL:
    file: lib/Courier/Filter/Module/DNSBL.pm
    version: 0.11
  Courier::Filter::Module::Header:
    file: lib/Courier/Filter/Module/Header.pm
    version: 0.11
  Courier::Filter::Module::MIMEParts:
    file: lib/Courier/Filter/Module/MIMEParts.pm
    version: 0.11
  Courier::Filter::Module::SPF:
    file: lib/Courier/Filter/Module/SPF.pm
    version: 0.11
  Courier::Message:
    file: lib/Courier/Message.pm
    version: 0.11
  MIME::Words::Better:
    file: lib/Courier/Message.pm
    version: 0.11
generated_by: Module::Build version 0.21
